### ISSUE TITLE
Request: SCSS Version

### ISSUE THREAD

**Issue by ColeTownsend** [P233/Rebar#1]
Any way you'll support SCSS? I'd love to see that here, or help work on it.

**Comment by P233** [comment]
Hi @ColeTownsend, Rebar definitely supports SCSS syntax. and it's actually recommend to use SCSS syntax rather than indented Sass syntax. Because the indented syntax doesn't support multiline expressions.

I personally prefer using the indent Sass syntax, but when I need to use the map feature I switch to SCSS syntax. Please see the styles of Rebar website as an example: https://github.com/P233/rebar.io/tree/gh-pages/_sass

**Comment by ColeTownsend** [comment]
Awesome!
